### ISSUE TITLE
Can't exec nmap

### ISSUE THREAD

**Issue by baphometadata** [cPanelTechs/SSE#8]
Have had some variant of this error on the last three servers I've run this on, so making a note to look into it:

Can't exec "nmap": No such file or directory at /dev/fd/63 line 683, <FILE> line 70.
Can't exec "nmap": No such file or directory at /dev/fd/63 line 712, <FILE> line 70.
Can't exec "nmap": No such file or directory at /dev/fd/63 line 751, <FILE> line 70.

**Comment by chrisice** [comment]
I think that's because i didn't use the full path to the script  in the subroutines. 

            my @scan = qx/nmap localhost -p 25/;

 I'll assign this one to myself and fix it when I get some time.

**Comment by chrisice** [comment]
Looks like it's because nmap isn't installed on the servers.

Can't exec "nmap": No such file or directory at sse.pl line 683, <FILE> line 1.
Can't exec "nmap": No such file or directory at sse.pl line 712, <FILE> line 1.
Can't exec "nmap": No such file or directory at sse.pl line 751, <FILE> line 1.
[~]cPs# vim sse.pl
[~]cPs# which nmap

Looks like im going to have to find a different way to do it

**Comment by batsyphus** [comment]
Yeah -- that was my assumption of what the problem was.   A lot of servers don't have nmap (or telnet).

Maybe there's a way using lsof -i?
